### ISSUE TITLE
switchaudiosource path not correct

### ISSUE THREAD

**Issue by Jeffr89** [beet/alfred_audio_switcher#1]
Hi @beet,
I've installed switchaudiosource with homebrew and it has been installed in the homebrew bin path "/opt/homebrew/bin"

To let your workflow works I had to replace all the "/usr/bin" path in the scripts with the homebrew's one.

**Comment by beet** [comment]
Thanks @Jeffr89, I'll see if I can find a way to work with different paths.

**Comment by beet** [comment]
Had a crack at using relative paths, but no joy unfortunately. I'd have to abstract the path out to a workflow variable.

**Comment by Jeffr89** [comment]
It is a good idea!
@beet another idea is to implement an if else case to determine the right path, but maybe ur workflow variable solution is cleaner.

**Comment by beet** [comment]
> @beet another idea is to implement an if else case to determine the right path, but maybe ur workflow variable solution is cleaner.

🤔 if it's doable, that would be even better! Might be able to look for the binary in various paths and write that back to a workflow variable, or raise an alert if it's not found prompting to enter it manually.

**Comment by Jeffr89** [comment]
> 🤔 if it's doable, that would be even better! Might be able to look for the binary in various paths and write that back to a workflow variable, or raise an alert if it's not found prompting to enter it manually.

I'm working on it 😄

**Comment by Jeffr89** [comment]
pull request submitted!

**Comment by beet** [comment]
Should be resolved now by #2 and #3.

Thanks @Jeffr89!
